project:
  type: website
  output-dir: docs

website:
  title: "Dhanshree Dhrafani's Data Insights"
  author: "Dhanshree Dhrafani"
  description: |
    Welcome to my personal data exploration blog, where I analyze and visualize various topics
    through the lens of data. Here, you'll find insights into my journey with data analysis and classic literature.
  format:
    html:
      theme: cosmo
      css: styles.css
      toc: true
      toc-depth: 2
      code-tools: true
  site-footer:
    - text: "GitHub"
      url: "https://github.com/ETC5523-2024/assignment-3-v2-creating-a-blog-Dhanshree-dhrafani"
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Blog"
        href: posts/blog.qmd
