project:
  type: website
  output-dir: docs

website:
  title: "Dhanshree Dhrafani's Data Insights"

  navbar:
    right:
      - text: "About"
        href: index.qmd
      - text: "Blog"
        href: blog.qmd

format:
  html:
    theme: cosmo
    css: styles.css
